name: ryc_desafio_do_modulo_basico
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mocktail: ^1.0.3
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  dio: ^5.4.3+1
  injectable: ^2.4.2
  get_it: ^7.7.0

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  build_runner: ^2.4.10
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.1

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
